name: refine
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - ld_impl_linux-64=2.40
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=1.1.1w
  - pip=24.2
  - python=3.10.6
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - bleach==6.1.0
      - certifi==2022.12.7
      - charset-normalizer==2.0.12
      - curves==0.1.5
      - cycler==0.12.1
      - easydict==1.9
      - einops==0.8.0
      - filelock==3.9.0
      - fonttools==4.43.1
      - fsspec==2024.10.0
      - grpcio==1.68.1
      - h5py==3.12.1
      - huggingface-hub==0.26.2
      - idna==3.4
      - imageio==2.36.1
      - jinja2==3.1.2
      - joblib==1.4.2
      - kaggle==1.6.4
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - lpips==0.1.4
      - markdown==3.7
      - markupsafe==2.1.2
      - matplotlib==3.5.1
      - mpmath==1.3.0
      - natsort==8.4.0
      - networkx==3.0
      - numpy==1.24.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.6.77
      - nvidia-nvtx-cu12==12.1.105
      - opencv-contrib-python==4.10.0.84
      - opencv-python==4.8.1.78
      - packaging==23.2
      - pandas==2.1.1
      - pilgram==1.2.1
      - pillow==11.1.0
      - piqa==1.3.1
      - protobuf==5.29.2
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-slugify==8.0.3
      - pytz==2023.3.post1
      - pyyaml==6.0.2
      - requests==2.26.0
      - safetensors==0.4.5
      - scikit-image==0.25.0
      - scikit-learn==1.5.0
      - scipy==1.15.0
      - seaborn==0.11.2
      - six==1.16.0
      - some-package==0.1
      - sympy==1.12
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - termcolor==1.1.0
      - text-unidecode==1.3
      - threadpoolctl==3.5.0
      - tifffile==2024.12.12
      - timm==1.0.11
      - toml==0.10.2
      - torch==2.1.0
      - torchaudio==2.1.0
      - torchvision==0.16.0
      - tqdm==4.62.3
      - triton==2.1.0
      - typing-extensions==4.4.0
      - tzdata==2023.3
      - urllib3==1.26.13
      - vit-pytorch==1.8.7
      - webencodings==0.5.1
      - werkzeug==3.1.3
      - wget==3.2
